name: Certbot SSL

on:
  workflow_call:
    inputs:
      domain:
        description: "Primary domain (e.g. yourdomain.com)"
        required: true
        type: string
      www:
        description: "Also include www subdomain?"
        required: true
        type: boolean
        default: false
      email:
        description: "Email for Let's Encrypt notifications"
        required: true
        type: string
      backend_port:
        description: "Backend app port (default: 8000)"
        required: false
        default: "8000"
        type: string
      nginx_generator_link:
        description: "File link to nginx generator"
        required: true
        type: string

jobs:
  certbot:
    name: Generate Nginx Config & Issue SSL Certificate
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ inputs.domain }}
      WWW: ${{ inputs.www }}
      EMAIL: ${{ inputs.email }}
      PORT: ${{ inputs.backend_port }}
      NGINX_URL: ${{ inputs.nginx_generator_link }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VM host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run script & configure Certbot
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo wget -qO- '$NGINX_URL' | sudo bash -s -- '$DOMAIN' '$PORT' '$WWW' '$EMAIL'"
